### ISSUE TITLE
Link to the solution

### ISSUE THREAD

**Issue by lukas-tr** [htl-perg-2019-20-5ahif/trippin-exercise-lukas-tr#1]
@not-matthias and I collaborated on creating a less than 30 line version. 
I don't know what "link to solution" means, but here are all created users although I'm not sure how long they are saved: https://services.odata.org/TripPinRESTierService/(S(5yramqng23p4qsvfuy0ekoym))/People

**Comment by rstropek** [comment]
Nice 👍
